# Generated by Django 5.2.11 on 2026-03-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCurricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('nacional', 'Nacional (NAP)'), ('provincial', 'Provincial (Currículum Córdoba)'), ('municipal', 'Municipal (Actualizaciones)')], max_length=20)),
                ('tipo', models.CharField(choices=[('nap_ciclo', 'NAP por Ciclo'), ('mcc', 'Marco Curricular Común'), ('orientaciones', 'Orientaciones Pedagógicas y Didácticas'), ('progresiones', 'Progresiones de Aprendizaje'), ('actualizacion', 'Actualización Curricular')], max_length=20)),
                ('ciclo', models.CharField(choices=[('todos', 'Todos los ciclos'), ('primero', 'Primer Ciclo (1°, 2°, 3°)'), ('segundo', 'Segundo Ciclo (4°, 5°, 6°)')], default='todos', max_length=20)),
                ('materia', models.CharField(choices=[('todas', 'Todas las materias'), ('matematicas', 'Matemática'), ('lengua', 'Lengua y Literatura'), ('ciencias_naturales', 'Ciencias Naturales'), ('ciencias_sociales', 'Ciencias Sociales')], default='todas', max_length=30)),
                ('provincia', models.CharField(blank=True, choices=[('cordoba', 'Córdoba'), ('buenos_aires', 'Buenos Aires'), ('santa_fe', 'Santa Fe'), ('mendoza', 'Mendoza'), ('tucuman', 'Tucumán'), ('entre_rios', 'Entre Ríos'), ('salta', 'Salta'), ('misiones', 'Misiones'), ('chaco', 'Chaco'), ('corrientes', 'Corrientes'), ('santiago_del_estero', 'Santiago del Estero'), ('san_juan', 'San Juan'), ('jujuy', 'Jujuy'), ('rio_negro', 'Río Negro'), ('neuquen', 'Neuquén'), ('formosa', 'Formosa'), ('chubut', 'Chubut'), ('san_luis', 'San Luis'), ('catamarca', 'Catamarca'), ('la_rioja', 'La Rioja'), ('la_pampa', 'La Pampa'), ('santa_cruz', 'Santa Cruz'), ('tierra_del_fuego', 'Tierra del Fuego'), ('caba', 'Ciudad Autónoma de Buenos Aires')], help_text='Solo para documentos provinciales', max_length=50)),
                ('municipio', models.CharField(blank=True, help_text='Solo para actualizaciones municipales', max_length=100)),
                ('año_actualizacion', models.IntegerField(blank=True, help_text='Año de la actualización (ej: 2023)', null=True)),
                ('archivo', models.FileField(upload_to='curricula/')),
                ('procesado', models.BooleanField(default=False)),
                ('chunks_count', models.IntegerField(default=0, help_text='Fragmentos en ChromaDB')),
                ('vigente', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Curricular',
                'verbose_name_plural': 'Documentos Curriculares',
                'ordering': ['nivel', 'tipo', 'materia'],
            },
        ),
    ]
