# Generated by Django 5.2.11 on 2026-03-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('grado', models.IntegerField(choices=[(1, '1° Grado'), (2, '2° Grado'), (3, '3° Grado'), (4, '4° Grado'), (5, '5° Grado'), (6, '6° Grado')])),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1)),
                ('division', models.CharField(choices=[('A', 'División A'), ('B', 'División B'), ('C', 'División C'), ('D', 'División D')], default='A', max_length=1)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='docentes.institucion')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('NEE', 'Rezago Significativo'), ('LP', 'Logros en Proceso'), ('LE', 'Logros Esperados')], default='LE', max_length=4)),
                ('nota_contextual', models.TextField(blank=True, help_text='Ej: No tiene lectoescritura consolidada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='planificacion.alumno')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_alumnos', to='docentes.asignaciondocente')),
            ],
            options={
                'verbose_name_plural': 'Niveles de Alumnos',
                'unique_together': {('alumno', 'asignacion')},
            },
        ),
        migrations.CreateModel(
            name='HistorialNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_anterior', models.CharField(choices=[('NEE', 'Rezago Significativo'), ('LP', 'Logros en Proceso'), ('LE', 'Logros Esperados')], max_length=4)),
                ('nivel_nuevo', models.CharField(choices=[('NEE', 'Rezago Significativo'), ('LP', 'Logros en Proceso'), ('LE', 'Logros Esperados')], max_length=4)),
                ('motivo', models.TextField(blank=True, help_text='Razón del cambio de nivel')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='planificacion.nivelalumno')),
            ],
            options={
                'verbose_name_plural': 'Historial de Niveles',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_original', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('actividades_json', models.JSONField(blank=True, default=dict)),
                ('fue_util', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='docentes.asignaciondocente')),
            ],
            options={
                'verbose_name_plural': 'Planificaciones Generadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True, help_text='Contenido en texto del proyecto')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('procesado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='docentes.asignaciondocente')),
            ],
            options={
                'verbose_name_plural': 'Proyectos de Aula',
                'ordering': ['-created_at'],
            },
        ),
    ]
