# Generated by Django 5.2.11 on 2026-03-11 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectoaula',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Proyectos de Aula (Deprecado)'},
        ),
        migrations.CreateModel(
            name='DocumentoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto Áulico'), ('planificacion_anual', 'Planificación Anual')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos_docentes/')),
                ('contenido', models.TextField(blank=True, help_text='Contenido en texto extraído del archivo')),
                ('procesado', models.BooleanField(default=False)),
                ('chunks_generados', models.IntegerField(default=0)),
                ('error_procesamiento', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='docentes.asignaciondocente')),
            ],
            options={
                'verbose_name': 'Documento Docente',
                'verbose_name_plural': 'Documentos Docentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
