# Generated by Django 5.2.11 on 2026-03-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_proyectoaula_options_documentodocente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='observaciones',
        ),
    ]
