# Generated by Django 5.2.11 on 2026-03-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_remove_observaciones_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificaciongenerada',
            name='es_resumen',
            field=models.BooleanField(default=False, help_text='True si este mensaje es un resumen comprimido del historial anterior'),
        ),
    ]
