# Generated by Django 5.2.11 on 2026-03-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('planificacion', '0004_add_es_resumen_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodocente',
            name='grado',
            field=models.CharField(blank=True, help_text="Grado al que aplica (ej: '2', '5-6', 'todos')", max_length=10),
        ),
        migrations.AddField(
            model_name='documentodocente',
            name='grados_lista',
            field=models.CharField(blank=True, help_text="Grados separados por coma (ej: '1,2,3,4,5,6')", max_length=50),
        ),
        migrations.AddField(
            model_name='documentodocente',
            name='materias_confirmadas',
            field=models.CharField(blank=True, help_text='Materias confirmadas por el docente', max_length=200),
        ),
        migrations.AddField(
            model_name='documentodocente',
            name='materias_detectadas',
            field=models.CharField(blank=True, help_text='Materias detectadas automáticamente', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentodocente',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='docentes.asignaciondocente'),
        ),
    ]
