# Generated by Django 5.2.11 on 2026-03-10 22:40

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('localidad', models.CharField(default='Córdoba', max_length=100)),
                ('provincia', models.CharField(choices=[('cordoba', 'Córdoba'), ('buenos_aires', 'Buenos Aires'), ('santa_fe', 'Santa Fe'), ('mendoza', 'Mendoza'), ('tucuman', 'Tucumán'), ('entre_rios', 'Entre Ríos'), ('salta', 'Salta'), ('misiones', 'Misiones'), ('chaco', 'Chaco'), ('corrientes', 'Corrientes'), ('santiago_del_estero', 'Santiago del Estero'), ('san_juan', 'San Juan'), ('jujuy', 'Jujuy'), ('rio_negro', 'Río Negro'), ('neuquen', 'Neuquén'), ('formosa', 'Formosa'), ('chubut', 'Chubut'), ('san_luis', 'San Luis'), ('catamarca', 'Catamarca'), ('la_rioja', 'La Rioja'), ('la_pampa', 'La Pampa'), ('santa_cruz', 'Santa Cruz'), ('tierra_del_fuego', 'Tierra del Fuego'), ('caba', 'Ciudad Autónoma de Buenos Aires')], default='cordoba', max_length=50)),
                ('municipio', models.CharField(default='Córdoba Capital', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='docentes.institucion')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='docentes.institucion')),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'unique_together': {('nombre', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField(choices=[(1, '1° Grado'), (2, '2° Grado'), (3, '3° Grado'), (4, '4° Grado'), (5, '5° Grado'), (6, '6° Grado')])),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1)),
                ('division', models.CharField(choices=[('A', 'División A'), ('B', 'División B'), ('C', 'División C'), ('D', 'División D')], default='A', max_length=1)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='docentes.materia')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de Docentes',
                'unique_together': {('docente', 'materia', 'grado', 'division', 'turno')},
            },
        ),
    ]
