# Generated by Django 5.2.11 on 2026-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondocente',
            name='grado',
            field=models.IntegerField(choices=[(-2, 'Sala de 4 (Jardín)'), (-1, 'Sala de 5 (Jardín)'), (1, '1° Grado'), (2, '2° Grado'), (3, '3° Grado'), (4, '4° Grado'), (5, '5° Grado'), (6, '6° Grado')]),
        ),
    ]
